clc; close all; clear all;
t= -2*pi : 0.001 : 2*pi;
x=sin(t) + cos(t); % x(t)=sint(t)+cos(t)
subplot(3, 2, 1);
plot(t, x);
grid;
xlabel('time');
ylabel('amplitude');
title('x(t): input signal x(t)');
y=sin(-t) + cos(-t); % y(t)=x(-t)
subplot(3, 2, 2);
plot(t, y); grid;
xlabel('time');
ylabel('amplitude');
title(' x(-t): reflected version of x(t)');
even=(x+y)/2;
subplot(3, 2, 3);
plot(t, even); grid;
xlabel('time');
ylabel('amplitude');
title('even part of the signal (even symmetric)') ;
odd=(x-y)/2;
subplot(3, 2, 4);
plot(t, odd); grid;
xlabel('time');
ylabel('amplitude');
title('odd part of the signal (anti-symmetric)');
sum_signal= even + odd;
subplot(3, 2, 5);
plot(t,sum_signal); grid;
xlabel('time');
ylabel('amplitude');
title('sum signal = odd + even = given signal x(t)');